ベクトル式を扱う

- ベクトルを扱うサンプルコードを書いて。

In [1]:
import numpy as np

# Create a vector
vector = np.array([1, 2, 3])

# Print the vector
print("Vector:", vector)

# Calculate the length of the vector
length = np.linalg.norm(vector)
print("Length of the vector:", length)

# Calculate the dot product of two vectors
vector2 = np.array([4, 5, 6])
dot_product = np.dot(vector, vector2)
print("Dot product of the two vectors:", dot_product)

# Calculate the cross product of two vectors
cross_product = np.cross(vector, vector2)
print("Cross product of the two vectors:", cross_product)

Vector: [1 2 3]
Length of the vector: 3.7416573867739413
Dot product of the two vectors: 32
Cross product of the two vectors: [-3  6 -3]


行列を扱う

- 行列を扱うサンプルコードを書いて

In [5]:
import numpy as np

# Create a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Print the matrix
print("Matrix:")
print(matrix)

# Calculate the transpose of the matrix
transpose = np.transpose(matrix)
print("Transpose of the matrix:")
# Check if the matrix is singular
if np.linalg.det(matrix) == 0:
    print("Matrix is singular, cannot calculate inverse.")
else:
    # Calculate the inverse of the matrix
    inverse = np.linalg.inv(matrix)
    print("Inverse of the matrix:")
    print(inverse)

print("Matrix multiplication:")
# Create a matrix
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
# Multiply the two matrices
product = np.dot(matrix1, matrix2)
print(product)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of the matrix:
Matrix is singular, cannot calculate inverse.
Matrix multiplication:
[[19 22]
 [43 50]]
